---

language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
  - DOCKER_IMAGE_BASE=idealista/jdk:8u252-stretch-openjdk-headless TOMCAT_VERSION=9.0.43
  - DOCKER_IMAGE_BASE=idealista/jdk:8u252-stretch-openjdk-headless TOMCAT_VERSION=8.5.63
  - DOCKER_IMAGE_BASE=idealista/jdk:8u252-stretch-openjdk-headless TOMCAT_VERSION=7.0.108
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.7-buster-openjdk-headless TOMCAT_VERSION=9.0.43
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.7-buster-openjdk-headless TOMCAT_VERSION=8.5.63
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.7-buster-openjdk-headless TOMCAT_VERSION=7.0.108
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.6-stretch-openjdk-headless TOMCAT_VERSION=9.0.43
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.6-stretch-openjdk-headless TOMCAT_VERSION=8.5.63
  - DOCKER_IMAGE_BASE=idealista/jdk:11.0.6-stretch-openjdk-headless TOMCAT_VERSION=7.0.108
  - DOCKER_IMAGE_BASE=idealista/jdk:8u265-focal-openjdk-headless TOMCAT_VERSION=9.0.43
  - DOCKER_IMAGE_BASE=idealista/jdk:8u265-focal-openjdk-headless TOMCAT_VERSION=8.5.63
  - DOCKER_IMAGE_BASE=idealista/jdk:8u265-focal-openjdk-headless TOMCAT_VERSION=7.0.108
  - DOCKER_IMAGE_BASE=idealista/jdk:14.0.1-focal-openjdk-headless TOMCAT_VERSION=9.0.43
  - DOCKER_IMAGE_BASE=idealista/jdk:14.0.1-focal-openjdk-headless TOMCAT_VERSION=8.5.63
  - DOCKER_IMAGE_BASE=idealista/jdk:14.0.1-focal-openjdk-headless TOMCAT_VERSION=7.0.108
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
