---
- name: Tomcat | Install
  import_tasks: install.yml
  tags:
    - tomcat_install

- name: Tomcat | Service
  import_tasks: service.yml
  tags:
    - tomcat_service

- name: Tomcat | Config
  import_tasks: config.yml
  tags:
    - tomcat_config

- name: Tomcat | Agent config
  import_tasks: agent.yml
  tags:
    - tomcat_agent_config
  when: tomcat_agents_config is defined

- name: Tomcat | Deploy
  import_tasks: deploy.yml
  tags:
    - tomcat_deploy
