---

- name: Verify
  hosts: all
  become: true
  vars:
    goss_version: v0.4.4
    goss_arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64'}}"
    goss_dst: /usr/local/bin/goss
    goss_sha256sum: "{{ 'fd76103dd6f373d48317b19542e4556cd27a06d415638561d410dfc139af19c8' if ansible_facts.architecture == 'aarch64' else '1c4f54b22fde9d4d5687939abc2606b0660a5d14a98afcd09b04b793d69acdc5'}}"
    goss_url: "https://github.com/goss-org/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    goss_test_directory: /tmp
    goss_format: documentation
    tomcat_version: "{{ molecule_yml.provisioner.inventory.group_vars.tomcat.tomcat_version }}"
    goss_sleep: 1s
    goss_retry_timeout: 0
  tasks:
    - name: Download and install Goss
      get_url:
        url: "{{ goss_url }}"
        dest: "{{ goss_dst }}"
        sha256sum: "{{ goss_sha256sum }}"
        mode: 0755
      register: download_goss
      until: download_goss is succeeded
      retries: 3

    - name: Copy Goss tests to remote
      template:
        src: "{{ item }}"
        dest: "{{ goss_test_directory }}/{{ item | basename }}"
      with_fileglob:
        - "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/test_*.yml"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_*.yml"
      register: test_files

    - name: Execute Goss tests
      command: "{{ goss_dst }} -g {{ item }} validate --format {{ goss_format }} -s {{ goss_sleep }} -r {{ goss_retry_timeout }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      ignore_errors: true

    - name: Display details about the Goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"